# Generated by Django 5.2.7 on 2025-11-08 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="UserProfile",
        ),
    ]
